version: "3.8"

services:
    homeowl_postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: odini
            POSTGRES_PASSWORD: swimming_in_the_sunshine_well
            POSTGRES_DB: home_owl_db
        ports:
            - "5432:5432"
